// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0u7aJPlJwKI8RzcC3FPNl_lH2Ll7-BA',
    appId: '1:906090292152:web:e8bfe080bf3ef369b1a54d',
    messagingSenderId: '906090292152',
    projectId: 'gfh-farm-management',
    authDomain: 'gfh-farm-management.firebaseapp.com',
    storageBucket: 'gfh-farm-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADe0t0SB0Akm0avC4t2O_uKOirSx7DWmA',
    appId: '1:906090292152:android:72f52465adbae579b1a54d',
    messagingSenderId: '906090292152',
    projectId: 'gfh-farm-management',
    storageBucket: 'gfh-farm-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChTipfVqfknlqXUFEg90iYHA9G7c0Hg9M',
    appId: '1:906090292152:ios:af2413b158d09944b1a54d',
    messagingSenderId: '906090292152',
    projectId: 'gfh-farm-management',
    storageBucket: 'gfh-farm-management.firebasestorage.app',
    iosBundleId: 'com.example.truckLedgerV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChTipfVqfknlqXUFEg90iYHA9G7c0Hg9M',
    appId: '1:906090292152:ios:af2413b158d09944b1a54d',
    messagingSenderId: '906090292152',
    projectId: 'gfh-farm-management',
    storageBucket: 'gfh-farm-management.firebasestorage.app',
    iosBundleId: 'com.example.truckLedgerV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz0u7aJPlJwKI8RzcC3FPNl_lH2Ll7-BA',
    appId: '1:906090292152:web:be0e7150bbd2a967b1a54d',
    messagingSenderId: '906090292152',
    projectId: 'gfh-farm-management',
    authDomain: 'gfh-farm-management.firebaseapp.com',
    storageBucket: 'gfh-farm-management.firebasestorage.app',
  );
}
